config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  resources :plans

  root 'pages#home'

  get 'projects' => 'pages#projects'
  get 'dashboard' => 'pages#dashboard'
  get 'about' => 'pages#about'

end

app/views/pages/about.html.erb
<header class="parallax parallax--header js-parallax--header">
    <div class="parallax__bg" style="background-image: url(<%= image_path('header4.jpg')%>);"></div>
    <div class="parallax__cta parallax__cta--mini parallax__cta--bl">
        <h2>About</h2>
    </div>
</header>

<section class="content">

    <div class="container">

        <div class="row">
            <div class="col-sm-12 col-md-8 col-md-offset-2">
                <p>The Collaborative Design Toolkit is the product of a three year long research project conducted by Dan Bagnall whilst undertaking a Master of Architecture at Birmingham School of Architecture. The research focused on participation of local stakeholders in architecture and collaboration between these stakeholders, powerholders such as councils and developers and architects. Research was not only conducted traditional theory and case study led approach, but also through practical research on a number of engagement projects. During this time it became evident a tool was required to facilitate the initiation of such projects, this led to the creation of the Collaborative Design Toolkit.</p>

                <p>The purposed of the Toolkit is to facilitate engagement between stakeholders, powerholders and architects, developing new connections and partnerships, which in turn may lead to collaboration between all parties over decisions regarding the built environment. Although the Toolkit is currently at a prototype stage, developed as part of the submission for the MArch research project, it is open for live testing. It is hoped through continual testing and dialogue with users it will develop further, evolving to encompass requirements and suggestions from users.</p>

                <p>If you have used the Collaborative Design Toolkit and have feedback please send comments to: info@collaborativedesign.net
                </p>

                <!-- <%= image_tag "hill.jpg" %> -->

            </div>
        </div>

    </div>
</section>

app/views/pages/dashboard.html.erb
<div class="container">
    <h1>dashboard</h1>

    <% if admin_signed_in? %>
      <%= link_to :logout, destroy_admin_session_path, :method => :delete %>
    <% end %>
    <div class="table-container">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>want email?</th>
                    <th>email sent</th>

                    <th>Role</th>
                    <th>Partnerships</th>
                    <th>Scale</th>
                    <th>Opportunity</th>
                    <th>Timescale</th>
                    <th>Familiarity</th>
                    <th>Past Projects</th>
                    <th>Role Other</th>
                    <th>Resources</th>
                    <th>Funding How</th>
                    <th>Recruit?</th>
                </tr>
            </thead>
            <tbody>
                <% @plans.each do |plan| %>
                    <tr>
                        <td><%= plan.id %></td>
                        <td><%= plan.name %></td>
                        <td><%= plan.email %></td>
                        <td><%= plan.email_user_plan %></td>
                        <td><%= plan.email_sent %></td>

                        <td><%= plan.role %></td>
                        <td><ul>
                            <% plan.partnerships.each do |partner| %>
                                <% unless partner.blank? %>
                                    <li><%= partner %></li>
                                <% end %>
                            <% end %>
                        </ul></td>
                        <td><%= plan.scale %></td>
                        <td><%= plan.opportunity %></td>
                        <td>
                            <% case plan.timescale %>
                            <% when 1 %>
                                <%= "1 Month" %>
                            <% when 6 %>
                                <%= "1-6 Months" %>
                            <% when 12 %>
                                <%= "6+ Months" %>
                            <% end %>
                        </td>
                        <td><%= plan.familiarity %></td>
                        <td><%= plan.past_projects %></td>
                        <td><%= unless plan.role_other.blank? then plan.role_other else 'N/A' end %></td>
                        <td><ul>
                            <% plan.resources.each do |resource| %>
                                <% unless resource.blank? %>
                                    <li><%= resource %></li>
                                <% end %>
                            <% end %>
                        </ul></td>
                        <td><%= plan.funding_how ? 'yes' : 'no' %></td>
                        <td><%= plan.recruit_volunteers ? 'yes' : 'no' %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

</div>

app/views/pages/home.html.erb
<header class="intro" style="background-image: url(<%= image_path('spare3.jpg')%>);">
    <div class="intro__overlay"></div>
    <nav class="intro__nav" role="navigation">
        <%= link_to "Home", root_path, { :class => 'active'} %>
        <%= link_to "About", about_path %>
        <%= link_to "Projects", projects_path %>
        <%= link_to "New Plan", new_plan_path, { :class => 'btn'} %>
    </nav>
    <h1 class="intro__headline js-headline">Collaborative Design Toolkit</h1>

    <a href="#about" class="intro__continue js-smooth-scroll">
        <%= image_tag 'arrow.png' %>
    </a>
</header>

<section id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-10 col-md-offset-1">
                <p class="about__copy">The Collaborative Design Toolkit is a device to facilitate the engagement between communities, architects, politicians and other groups and individuals, who can collaborate to strive towards the development of a build environment which responds to the needs of the stakeholders it directly impacts. The Toolkit provides guidance on how to initiate conversations within a community, which can be used to create interest groups and guide future development.</p>
            </div>
        </div>
    </div>
</section>

<section class="parallax parallax--toolkit js-parallax--toolkit">
    <div class="parallax__bg" style="background-image: url(<%= image_path('header3.jpg')%>);"></div>
    <div class="parallax__cta parallax__cta--br">
        <h2>Toolkit</h2>
        <p>Create your own Collaborative Design plan. View online or have it emailed to you.</p>
        <%= link_to "Create a Plan", new_plan_path  %>
    </div>
</section>

<section class="project">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-lg-4">
                <a href="<%= projects_path %>">
                    <div class="project__item" style="background-image: url(<%= image_path('small.jpg')%>);">
                        <span>Small Workshops</span>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 col-sm-6 col-lg-4">
                <a href="<%= projects_path %>">
                    <div class="project__item" style="background-image: url(<%= image_path('art.jpg')%>);">
                        <span>Art Workshop</span>
                    </div>
                </a>
            </div>
            <div class="col-xs-12 col-sm-6 col-lg-4">
                <a href="<%= projects_path %>">
                    <div class="project__item" style="background-image: url(<%= image_path('arch.jpg')%>);">
                        <span>Architecture Workshop</span>
                    </div>
                </a>
            </div>

            <div class="col-xs-12">
                <div class="projects__cta">
                    <%= link_to "View All Projects", projects_path, {:class => ""} %>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="parallax parallax--author js-parallax--author">
    <div class="parallax__bg" style="background-image: url(<%= image_path('header2.jpg')%>);"></div>
    <div class="parallax__cta parallax__cta--tl">
        <h2>Dan Bagnall</h2>
        <p>The Toolkit is a prototypical device created as part of Dan Bagnall’s Master of Architecture dissertation.</p>
        <%= link_to "More about this project", about_path,{ :class=> "" }  %>
    </div>
</section>

app/views/pages/projects.html.erb
<header id="top" class="parallax parallax--header js-parallax--header">
    <div class="parallax__bg" style="background-image: url(<%= image_path('header1.jpg')%>);"></div>
    <div class="parallax__cta parallax__cta--mini parallax__cta--bl">
        <h2>Co Design Projects</h2>
    </div>
</header>


<section class="project js-projects-waypoints">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-lg-4">
                <a href="#small" class="js-smooth-scroll">
                    <div class="project__item" style="background-image: url(<%= image_path('small.jpg')%>);">
                        <span>Small Workshops</span>
                    </div>
                </a>
            </div>

            <div class="col-xs-12 col-sm-6 col-lg-4">
                <a href="#art" class="js-smooth-scroll">
                    <div class="project__item" style="background-image: url(<%= image_path('art.jpg')%>);">
                        <span>Art Workshop</span>
                    </div>
                </a>
            </div>

            <div class="col-xs-12 col-sm-6 col-lg-4">
                <a href="#arch" class="js-smooth-scroll">
                    <div class="project__item" style="background-image: url(<%= image_path('arch.jpg')%>);">
                        <span>Architecture Workshop</span>
                    </div>
                </a>
            </div>

        </div>
    </div>
</section>

<section id="small" class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-10 col-md-offset-1 content-inner">
                <h2>Small Workshop</h2>

                <h3>What?</h3>

                <p>Small workshops can be conducted through a variety of methods, but the purpose should be to engage stakeholders within a two-way conversation, unlike traditional consultation which is generally one-way. Tasks such as: wishing trees, draw your neighbourhood, traffic light analysis are all suitable.</p>

                <h3>Why?</h3>

                <p>These types of workshops are well suited for data collection, to demonstrate a need for projects. They are also perfect for creating connections and forming partnerships within communities. However, all engagement must be conducted considerately to ensure the connections established are meaningful. It is important not to deter stakeholders during this process, which could have a negative impact upon future engagement.</p>

                <h3>When?</h3>

                <p>Smaller workshops can be conducted at anytime within a project, however they are most suitable in the early stages of a project, when there is a greater need for creating connections and partnerships between groups.</p>

                <h3>Who?</h3>

                <p>These workshops do not require specialists, unlike other workshops. However it is important to ensure those conducted the workshops are engaging and enthusiastic in order to achieve the best outcomes.</p>

                <h3>How?</h3>

                <p>Small workshops are highly flexible, they can require as much or as little resources as are available. Workshops can be held in a variety of spaces, included on the streets if there are suitable means to do so. They do not require many materials, only paper, pens and possibly some modelling materials, therefore the budget required for these projects can be quite low.</p>

                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_smallworkshop02.jpg" %>
                    </div>
                     <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_smallworkshop03.jpg" %>
                    </div>
                     <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_smallworkshop04.jpg" %>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<section id="art" class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-10 col-md-offset-1 content-inner">
                <h2>Art Workshop</h2>

                <h3>What?</h3>

                <p>These workshops are led by artists who through the medium of art are able to engage conversations about issues or needs within an area. The work produced during the events does not have to represent the particular issues or needs, instead it is the conversations that take place simultaneously which are important.</p>

                <h3>Why?</h3>

                <p>Building confidence and opening up new opportunities, creating conversations.</p>

                <h3>When?</h3>

                <p>Art workshops are best conducted when facilitators have an understanding of the area they are working in, so the workshops do not deter prospective participants but instead build upon connections and deeper conversations..</p>

                <h3>Who?</h3>

                <p>Careful consideration should be made over the artist who will lead the engagement, they must be able to engage with those from a non-art background. They must also be able to use the process of making art to push forward a dialogue. It would be beneficial to partner with local artists who have a direct connection to the area, identifying these individuals could be achieved through desktop research or through prior engagement with stakeholders.</p>

                <h3>How?</h3>

                <p>Art workshops can require a large amount of materials and equipment, you budget must allow for these, prior discussion with artist(s) should be sought to identify what is needed. Additional budget must also be allowed for paying the artist for their time. These events can be held over one day to a number of days, dependant on the scale of your project and area. They will require a space to conduct the engagement, which ideally would be located within the area of concern.</p>

                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_artworkshop03.jpg" %>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_artworkshop04.jpg" %>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_artworkshop02.jpg" %>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<section id="arch" class="content">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-10 col-md-offset-1 content-inner">
                <h2>Architecture Workshop</h2>

                <h3>What?</h3>

                <p>Architecture workshops consist of engagement based around architectural centrepieces or models. Participants can be engaged through design and making.</p>

                <h3>Why?</h3>

                <p>The use of architectural structures or models allow engagement to be framed. They provide opportunities for engagement outside the traditional methods, which may have already fatigued participants. This type of project lends itself to questioning the spaces and environments which affect stakeholders.</p>

                <h3>When?</h3>

                <p>These types of projects are best conducted when the facilitators have a good knowledge of the area. If the area is unknown to facilitators it may be beneficial to run a smaller engagement workshop to create a presence within the area.</p>

                <h3>Who?</h3>

                <p>To conduct an architecture style workshop it would be advisable to partner with a representative from within the architectural profession. This would ideally be an individual or group from a local architecture practice or a school of architecture, who are able to enthuse participants to engage.</p>

                <h3>How?</h3>

                <p>Architecture workshops require a higher amount of resources when compared to other types of engagement, which must be considered when preparing a project budget. Firstly consideration of materials and tools needed to construct a centrepiece or architectural models must be made, also consider additional time needed to carry out this process. This type of project we require volunteers to assist with both construction and engagement. Finally, in most cases this type of project will need to be based at a location (as well as space to store materials and structures).</p>

                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_archworkshop02.jpg" %>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_archworkshop04.jpg" %>
                    </div>
                    <div class="col-sm-12 col-md-4">
                        <%= image_tag "projects_archworkshop03.jpg" %>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

<div class="js-lightbox lightbox">
    <img src="http://placehold.it/800x300">
</div>

<a href="#top" class="back-to-top js-back-to-top js-smooth-scroll">Back to Top</a>